---
- name: Make required directories
  ansible.builtin.file:
    path: $HOME/testdir-df
    state: directory

- name: Copy ALIASES to home directory
  ansible.builtin.copy:
    src: files/dotfiles/
    dest: ~/testdir-df/
