---
- name: Add HashiCorp's official GPG key
  ansible.builtin.rpm_key:
    key: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp Linux repo
  ansible.builtin.yum_repository:
    name: HashiCorp
    description: HashiCorp repo
    # should hopefully be 'fedora'
    baseurl: https://rpm.releases.hashicorp.com/{{ ansible_distribution|lower }}/hashicorp.repo
    state: present

- name: Check that HashiCorp packages (and related) are installed
  ansible.builtin.package:
    name:
      - packer
      - terraform
      - vagrant
      - whois
    state: latest