---
- name: "Install required Packages"
  ansible.builtin.import_tasks: packages.yml
  become: yes
  when: dotfile_install_packages
  tags:
    - install_packages

- name: "Move dotfiles in to place"
  ansible.builtin.import_tasks: dotfiles.yml
  when: dotfile_move_files
  tags:
    - move_files

- name: "Distribution specific actions"
  ansible.builtin.include_tasks: "distro-{{ ansible_distribution|lower }}.yml"
  tags:
    - distro_specific_actions

- name: "Install Hashicorp software"
  ansible.builtin.include_tasks: "hashicorp.yml"
  when: dotfile_install_hashicorp
  tags:
    - install_hashicorp