---
- name: "Check that REQUIRED packages are installed"
  ansible.builtin.package:
    name: 
      - curl
      - file
      - git
      - htop
      - openvpn
      - tmux
      - tree
    state: latest

- name: "Check that OPTIONAL packages are installed"
  ansible.builtin.package:
    name:
      - hugo
      - nmap
      - whois
    state: latest